name: dlbcl-analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3.0
  - r-tidyverse=2.0.0
  - r-ggplot2=3.4.3
  - r-pheatmap=1.0.12
  - r-rcolorbrewer=1.1_3
  - bioconductor-deseq2=1.42.0
  - bioconductor-tcgabiolinks=2.30.0
  - bioconductor-edger=4.0.0
  - bioconductor-enhancedvolcano=1.20.0
  - bioconductor-clusterprofiler=4.10.0
  - bioconductor-org.hs.eg.db=3.18.0
  - bioconductor-summarizedexperiment=1.32.0
  - r-data.table=1.14.8
  - r-devtools=2.4.5
  - r-biocmanager=1.30.20